server:
  shutdown: graceful

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${JDBC_URL}
    username: ${DB_USER}
    password: ${DB_PWD}
    hikari:
      max-lifetime: 600000

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    open-in-view: false

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

  jackson:
    property-naming-strategy: SNAKE_CASE

  lifecycle:
    timeout-per-shutdown-phase: 30s

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-exp: ${JWT_ACCESS_EXP}
  refresh-exp: ${JWT_REFRESH_EXP}

cloud:
  aws:
    region:
      static: ${AWS_S3_REGION:ap-northeast-2}
    stack:
      auto: false
    credentials:
      access-key: ${AWS_S3_ACCESS:s3_access}
      secret-key: ${AWS_S3_SECRET:s3_secret}

aws:
  s3:
    url: ${AWS_S3_URL}
    bucket: ${AWS_S3_BUCKET}
    profile-folder: ${AWS_S3_PROFILE_FOLDER:profile/}
    feed-folder: ${AWS_S3_FEED_FOLDER:feed/}
  ses:
    access-key: ${AWS_SES_ACCESS:ses_access}
    secret-key: ${AWS_SES_SECRET:ses_secret}
    region: ${AWS_SES_REGION:ap-northeast-2}
    email: ${AWS_SES_EMAIL:ses_email}

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
